name             'sprout-osx-Gnip'
maintainer       'Gnip'
maintainer_email 'admin@gnip.com'
license          'MIT'
description      'Installs/Configures sprout-osx-gnip'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
supports         'mac_os_x'
depends          'sprout-osx-base'
depends          'sprout-osx-settings'
depends          'dmg'